### ISSUE TITLE
Proposal: Adding Support for .flac Audio Files

### ISSUE THREAD

**Issue by alvarovegahd** [mbsantiago/whombat#1]
Hello,

Thank you very much for supporting open source bioacoustics with this tool! I was wondering if there are plans to support .flac. I would appreciate any guidance on this, in case that you have a roadmap or notes about this feature. Probably that is a [soundevent](https://github.com/mbsantiago/soundevent) feature more than a whombat feature? Or both?

Looking forward to your feedback and excited about the possibility of contributing to whombat.

Thanks,

**Comment by mbsantiago** [comment]
Hi @alvarovegahd!

Thanks for raising the issue of adding support to additional audio file formats! As you well guessed I've left the heavy lifting of audio loading to the `soundevent` package so let's keep that conversation on that repo. I'll keep this issue open in case others are looking for FLAC support in whombat.

**Comment by mbsantiago** [comment]
See the issue https://github.com/mbsantiago/whombat/issues/1 for more info.

**Comment by mbsantiago** [comment]
I believe that with the soundevent update Whombat should now be able to handle FLAC files and a host of other audio formats. Thanks @alvarovegahd for the help!
