### ISSUE TITLE
Executable not working (v4.1) on Mac OS (M1 chip)

### ISSUE THREAD

**Issue by sammlapp** [mbsantiago/whombat#7]
* Whombat version: 4.1
* Python version: N/A
* Operating System: Mac OS 12.6 on Apple M1 Pro

### Description
I downloaded the executable for Mac and double-clicked it

### What I Did

Here's the message displayed:
```

    Welcome to:

    __      _| |__   ___  _ __ ___ | |__   __ _| |_
    \ \ /\ / / '_ \ / _ \| '_ ` _ \| '_ \ / _` | __|
     \ V  V /| | | | (_) | | | | | | |_) | (_| | |_
      \_/\_/ |_| |_|\___/|_| |_| |_|_.__/ \__,_|\__|

    An ML-focused audio annotation tool.

    Please wait while Whombat starts up...
    
The environment does not allow connecting to the splash screen. Are the splash resources attached to the bootloader or did an error occur?
Traceback (most recent call last):
  File "PyInstaller/fake-modules/pyi_splash.py", line 98, in <module>
  File "<frozen os>", line 679, in __getitem__
KeyError: '_PYIBoot_SPLASH'

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by mbsantiago** [comment]
Hi @sammlapp,

Thanks for the issue. I've removed the splash screen and this should no longer be an issue (#17 ). I will be releasing a new version soon with the fix. Let me know if it doesn't work.

Santiago

**Comment by mbsantiago** [comment]
Hi @sammlapp, please try with the new release 0.6.3. I'll close this for now, but let me know if you re-encounter the issue.
